### ISSUE TITLE
Get DOI

### ISSUE THREAD

**Issue by fdiblen** [matchms/matchms-backup#10]
Get DOI, and make sure we have all relevant badges.
See:
 https://github.com/NLeSC/template

**Comment by jspaaks** [comment]
- [x] add a CITATION.cff using https://bit.ly/cffinit
- [x] Use [cffconvert](https://pypi.org/project/cffconvert/) to generate a .zenodo.json (or [here](http://bit.ly/cffconvert))
- [x] Enable GitHub-Zenodo integration
- [x] Make a release
- [x] get conceptDOI from Zenodo
- [x] get badge from Zenodo
- [x] Add badge to matchms README
- [x] Update the conceptDOI at https://www.research-software.nl/admin/software/matchms

**Comment by jspaaks** [comment]
citation data and zenodo metadata PR: https://github.com/NLeSC/spec2vec/pull/22

**Comment by jspaaks** [comment]
Before we can make a release, we need to ask @florian-huber if it's ok to make a release from this repo.

So blocked at the moment.

**Comment by jspaaks** [comment]
FYI renamed repo to avoid name clash with (later releases of) Spec2Vec
