### ISSUE TITLE
add_parent_mass filter function

### ISSUE THREAD

**Issue by fdiblen** [matchms/matchms-backup#105]
This issue is only about add_parent_mass filter.
add_parent_mass function need more explanation and it should be implemented.
We don't know what this filter does and why it is needed.
Other candidate filters are listed in #75

**Comment by florian-huber** [comment]
That indeed a very confusing part about the MS/MS or MS2 type of data. The input MGF usually will give a 'pepmass' which *should* be the precursor mass (#104). The precursor mass is the m/z, mass over charge ratio, that is measured. The parent mass the actual mass of the original molecule, so to get that right we need to know the charge of the precursor mass. 

I added a add_parent_mass function and a first test for it and made a PR #116 .
