### ISSUE TITLE
Can peaks be out of order?

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms-backup#111]
https://github.com/matchms/old-iomega-spec2vec/blob/216b8f8b5e4ffd320b4575326a05fb6c7cd28223/matchms/old/ms_similarity_classical.py#L543-L545

suggests that peaks can be out of order. Do we need a ``filtering/sort_by_mz.py`` to make sure?

**Comment by florian-huber** [comment]
After some thinking it looks more and more like a design choice. In the old code some parts needed peaks sorted by intensity, others sorted by m/z, but that was usually implemented as first computing step of those functions (which it also should be, the functions outcome shouldn't depend on the order of peaks it receives as input).
--> In that sense it is not strictly necessary.

However, it might still be nice to have a flag added to the getter functions for mz and intensities which would the user to allow to get either one sorted the way he/she wants.

Edit: 
### Additional remark/question:
It looks like the ``Spectrum`` mz and intensity getters and setters are currently still dummies, right?
Sorting could be implemented there. 

And related to that: I am a bit worried that having intensities and peak positions (mz) separate could lead to unexpected errors when used improperly.  When user for instance remove peaks or sort only one of them, the entire spectrum will be messed up. Would it be better to store things internally as tuples?

**Comment by fdiblen** [comment]
Just talked to @florian-huber. He will discuss it with @jspaaks and me.

**Comment by fdiblen** [comment]
We do not want to do extra sorting at this point.

**Comment by sverhoeven** [comment]
If sorting is needed it will be part of code that needs it not the Spectrum class
