### ISSUE TITLE
Cosine similarity function should also return number of matching peaks

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms-backup#118]
Now the newly implemented cosine score ``CosineGreedy`` (#112) returns the cosine score. But many MS people also use the number of matching peaks as a quality measure (it is actually a poor quality measure but it works to bring the number of false positives down). This is in principle easy to add to the CosineGreedy code but seems to conflict with the current implementation of the .sort and .top functions. 

I also expect that this will be more general and does not only apply to the cosine score (other scores might also return a score and some extra quality measures...). I imagine that the similarity measures could either return tuples (score, num_matches, ...), or they can be called in different ways?

```
from matchms.similarity import CosineGreedy
cosine_greedy = CosineGreedy("cosine-greedy", tolerance=5.0)
score = cosine_greedy(norm_spectrum_1, norm_spectrum_2)

score, n_matches = cosine_greedy(norm_spectrum_1, norm_spectrum_2, return_matches=True)
```

**Comment by jspaaks** [comment]
I think it's fine if similarity functions return a tuple. The question is what do we do with the tuple afterwards, specifically in https://github.com/matchms/matchms/blob/5572e7978c49e6436b61efc7393fd5619fab0e6f/matchms/Scores.py#L21

I think we have at least ~~two~~three options:

1. let ``Scores.scores`` be a 2-D array, where each element contains a tuple.
    a. This should already work, but ``sort``'ing (and therefore ``top``) then becomes ambiguous. You could mitigate that by asking users to supply their own comparator function as an argument to both ``top`` and ``sort``. This is not my preferred option. 
1. unpack the tuple into ``Scores.scores``'s 3rd dimension.
   - For this option to work, we could re-introduce labels on each output argument of the 1 similary function, and rename ``sort()`` back to ``sort_by(label)`` (and probably extend this to ``top`` as well).
   - and/or we could have a ``.flatten()`` which would return all results as rows of [reference object, query object, unpacked similarity function output arguments], and then let people do their own sorting/selecting/whatever else. The flattened results would have N*M rows and 2+Z columns, where N is the number of reference objects, M is the number of query objects, and Z is the number of elements in the tuple returned by the similarity function.
1. A combination of the above, where we leave ``Scores.scores`` 2-D, with every element a tuple. Then add a ``.flatten(unpack=True)`` that unpacks the ``.scores`` as in 2)

    We should then probably remove the ``.sort()`` and ``.top()`` to avoid confusion. Or, raise an Exception for calls to ``sort()`` or ``top()`` when the similarity function returns something else than a scalar number.

**Comment by fdiblen** [comment]
@fdiblen, @sverhoeven, @cwmeijer,  @florian-huber your input is required for this issue.

**Comment by sverhoeven** [comment]
- Option 4: Let `calculate_scores` return array of a Scores object. Each Scores object maps to an item returned by the  similarity function. 
    Scores class can then remain the same.

**Comment by sverhoeven** [comment]
* Option 5: iterator instead of sort(), top(), scores properties. 
	In Scores class store float or tuple that is returned by the similarity_function, the class will have iterator or generator which will each time yield a tuple with (query spectrum, reference spectrum, score, n_matches). The tuple (score, n_matches) returned by the similarity_function is unpacked. The order of the iterator will be first query and second reference spectrum. So first iterations will return the first query with all its reference spectrums + scores. The iterator will not be ordered on score. To order the references for each query a comparator function must be applied afterwards for example like

	```python
	scores = calculate_scores(queries, references, cosine_greedy, include_self_comparisons=False)
	from operator import itemgetter
	sorted_scores = sorted(scores, key=itemgetter(0, 2))
	# [(query spectrum, reference spectrum, score, n_matches)]

**Comment by jspaaks** [comment]
I like option 5. In addition, would it make sense to (re)introduce ``labels`` for the elements of the tuple returned by a similarity function (if indeed it does return a tuple), so you would get:

```python
cosine_greedy = CosineGreedy(labels=["cosine", "n_matches"])
scores = calculate_scores(queries,
                          references,
                          cosine_greedy)
```

Such that users could do 
```python
scores.sort(by="cosine")
```
and
```python
scores.top(10, by="cosine")
```

Although really what you want is something like
```python
scores[n_matches>threshold].top(10, by="cosine")
```
Is it possible to do something like https://stackoverflow.com/a/16033058?

**Comment by jspaaks** [comment]
Also, for iterating over ``Scores.scores``, this may be relevant https://numpy.org/doc/1.18/reference/generated/numpy.flatiter.html.

**Comment by jspaaks** [comment]
PR #159

**Comment by jspaaks** [comment]
Fixed in https://github.com/matchms/matchms/pull/159, closing.
