### ISSUE TITLE
Add select_by_metadata() function to filtering

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms-backup#124]
Both during the cleaning/preprocessing procedure as well as the post-processing it can become necessary to select a subset from a list of spectra based on their metadata.
A typical use-case would like this:
- Select all spectra which have the desired degree of metadata (e.g. have smiles and/or inchi).
- Select all spectra which belong into a certain class, e.g. ``ionmode == 'positive'``, or ``charge == -1``, or ``'orbitrap' in source_instrument.lower()``.

Of course that can also be quickly written as a loop over all spectrums, but I believe that a proper filter function would still be nicer. Or what do you think?

**Comment by jspaaks** [comment]
It depends. If you are absolutely sure you don't need any spectrums with ``ionmode=="positive"`` or you are only interested in spectrums that have ``"'orbitrap' in source_instrument.lower()"`` (not sure we have this last part btw), then you could either implement your own filter or do an inline list comprehension, such that you end up with a subset of the spectrums that you got from e.g. a file. In any case, I don't think this specific functionality is required by many other users, so I'd say it should not be part of ``matchms.filtering``.

If you are not sure if you can exclude everything except ``ionmode=="positive"`` or ``"'orbitrap' in source_instrument.lower()"``, you may choose to leave the respective spectrums in the list of query spectrums, but then you'll have to either:
- update the similarity function such that it returns the query ionmode (and / or reference ionmode), such that you can retrieve it later (once we implement something like https://github.com/matchms/matchms/issues/118#issuecomment-616653050).
- manipulate the result-without-``ionmode`` such that it will include an ``ionmode``.

**Comment by florian-huber** [comment]
Yes, sounds right, we can leave it out. So I will close this issue.
