### ISSUE TITLE
openbabel has contagious license

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms-backup#129]
https://tldrlegal.com/license/gnu-general-public-license-v2

**Comment by florian-huber** [comment]
Openbabel seems like a lot of pain. So far I didn't get the time to look at it enough. But I hope that I can soon try to look for alternatives. There are certainly several potential alternatives, but we would have to test them on a large number of conversions to find if they have a similar or better success rate.

Some alternatives I want to look into are:
- **rdkit** (also not a simple library, but we use it already anyway. However, I remember that in the past I got less correct conversions).
- **openeye** 
- **ChemSpider**, see e.g. https://www.inchi-trust.org/inchi-post/chemistry-programming-with-python-convert-a-smile-string-to-inchi-using-chemspider-tutorial/
- **PubChemPy**

**Comment by florian-huber** [comment]
I ran rdkit and openbabel on about 45000 inchi's from the actual dataset. Unfortunately I got a similar result than a year ago with rdkit retrieving far fewer smiles from the given inchi.
 
```python
from rdkit import Chem

smiles = Chem.MolToSmiles(Chem.MolFromInchi(inchi))
```

**Comment by florian-huber** [comment]
Some former issues I had with rdkit were solved, the performance of an rdkit based solution hence became comparable to an openbabel based implementation.
This has been added in form of PR #187, in which openbabel is also removed from the environment.
