### ISSUE TITLE
file pattern for tests

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms-backup#130]
In the tests that I wrote, I needed to include blocks like 
https://github.com/matchms/matchms/blob/5572e7978c49e6436b61efc7393fd5619fab0e6f/tests/test_select_by_intensity.py#L76-L81

, because pycharm would not stop at breakpoints. Since then I found out this is an issue with the coverage calculation, https://github.com/pytest-dev/pytest-cov/issues/131. We could opt to change
https://github.com/matchms/matchms/blob/0e226261fabe557ba65589b7f14d00cf8c0e454d/setup.cfg#L14
to ``--no-cov`` and do the coverage calculation only in ci or only on sonarcloud, but not locally.

I we choose to go that way, we can remove the ``if __name__`` blocks from the test files.

**Comment by fdiblen** [comment]
To close this issue:
- [ ] We should remove if statements (line 76) in all the tests and update setup.cfg file with `--no-cov` options.
