### ISSUE TITLE
cast charge to int in add_parent_mass filter

### ISSUE THREAD

**Issue by fdiblen** [matchms/matchms-backup#132]
We should fix the conversion mentioned in: 
https://github.com/matchms/matchms/pull/116#pullrequestreview-394667406

**Comment by jspaaks** [comment]
some questions I had:
- is the charge you're getting from pyteomics not already an int?
- why is a float representation of an int not good enough?

**Comment by jspaaks** [comment]
ping @florian-huber

**Comment by florian-huber** [comment]
Yes, it should be an int (I believe it was just a left-over from former code where charges could also be string fields). I removed it in PR #158 .
