### ISSUE TITLE
how to add docstrings

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms-backup#137]
maybe we can use a tool like https://pypi.org/project/docstr-coverage/

**Comment by cwmeijer** [comment]
I like the tool. Two issues:
The tool doesn't seem to have an option to ignore private methods/functions such as ignore all functions that start with _.
Our code has lots of place holder docstrings which will make the tool think that everything is fine while actual content needs to be added.

I think it doesn't make sense to make us comment every private method/function as well, it will even demotivate people from refactoring code into small functions. What do you think?

I haven't found another tool yet that does have this option.

**Comment by jspaaks** [comment]
Looks like you can ignore private methods by adding a ignore pattern file and then pointing to that with ``--docstr-ignore-file=<filepath>``

I guess we could just remove the placeholder strings. I think I added them to see how the methods showed up in readthedocs. Which reminds me, https://github.com/matchms/matchms/issues/128

**Comment by cwmeijer** [comment]
Thought of another issue though. If we let this run as part of CI, this will fail every PR that doesn't have docstrings yet. I don't mind, but I think this is a bit harsh and makes it difficult to split tasks into subtasks production_code/tests/documentation. 

If the above issue can be solved or isn't such an issue after all then I'm very positive about adding the tool to our CI.

**Comment by jspaaks** [comment]
working on it here https://github.com/matchms/matchms/pull/157

**Comment by jspaaks** [comment]
Possible other tool https://www.sphinx-doc.org/en/master/usage/extensions/coverage.html

**Comment by sverhoeven** [comment]
Or https://www.sphinx-doc.org/en/master/usage/extensions/coverage.html
