### ISSUE TITLE
Make a Conda package

### ISSUE THREAD

**Issue by fdiblen** [matchms/matchms-backup#14]
See:
https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs.html
https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html

**Comment by cwmeijer** [comment]
blocked by ~~#1~~ #12

**Comment by jspaaks** [comment]
This issue can be closed when https://github.com/matchms/matchms/pull/68 is merged.
