### ISSUE TITLE
Milestone: redo originial pre-processing using matchms

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms-backup#141]
[edit] Updated 28/04/2020

I am currently looking into what is still missing to implement the full original preprocessing workflow from the iOMEGA project using matchms.

### Data
I use the raw data I got form our collaborators last summer (several folders with mgf files called "speclibs"). For now I skip the importing metadata step and did this in a notebook (first about 10 cells of https://github.com/iomega/Spec2Vec/blob/master/notebooks/Spec2Vec_01_MGF_from_gnps_library_search.ipynb), it essentially means that I combined the speclib mgf files with extra metadata that the collaborators provided me in form of a json file. I then also fixed the resulting MGF by replacing charges "-1+" with "-1", because "-1+" was not working with pyteomics. 

**You should have received a surfdrive link to the resulting mgf file.** 

### Code
I tried to run it with the current matchms filters, something like this:
```python
import os
from matchms.importing import load_from_mgf

# Import data from mgf file
path_data = '.'
mgf_file = os.path.join(path_data, 'all_gnps_added_metadata_fixed.mgf')
reference_spectrums_raw = load_from_mgf(mgf_file)

# Basic filtering of spectrums
from matchms.filtering import default_filters
from matchms.filtering import add_parent_mass

def apply_filters(s):
    s = default_filters(s)
    s = add_parent_mass(s)
    return(s)

reference_spectrums = [apply_filters(s) for s in reference_spectrums_raw]

# Select desired subset
spectrums_positive = [s.clone() for s in reference_spectrums if s.metadata["ionmode"] == 'positive']

# Further process spectrums
def process_spectrums(s):
    s = normalize_intensities(s)
    s = select_by_relative_intensity(s, intensity_from=0.01, intensity_to=1.0)
    s = select_by_mz(s, mz_from=0, mz_to=1000)
    s = require_minimum_number_of_peaks(s, n_required=5)
    return s

reference_spectrums_positive = [process_spectrums(s) for s in reference_spectrums_positive]

# Omit spectrums that didn't qualify for analysis
reference_spectrums_positive = [s.clone() for s in reference_spectrums_positive if s is not None]

# Final metadata cleaning
from matchms.filtering import clean_inchis, clean_inchikeys
from matchms.filtering import derive_inchi_from_smiles, derive_smiles_from_inchi
from matchms.filtering import derive_inchikey_from_inchi

def clean_metadata(s):
    s = clean_inchikeys(s)
    s = clean_inchis(s)
    s = derive_inchi_from_smiles(s)
    s = derive_smiles_from_inchi(s)
    s = derive_inchikey_from_inchi(s)
    return(s)

reference_spectrums_positive = [clean_metadata(s) for s in reference_spectrums_positive]
```
**Good news** is that with the recent changes this part for the first time worked without any errors!

### Still missing
What is still missing is some cleaning, converting, and lookup steps to improve the metadata quality.

- correct misplaced entries. The actual data contains inchikey and smiles given as inchi, both are now handled by ``clean_inchis()`` --> PR #176)
- ~~convert missing smiles from present inchis (done  --> #125 )~~
~~- convert missing inchis from present smiles (done --> #125)~~
~~- convert missing inchikeys from present inchis (done --> #125)~~
- "repair" broken inchi using pubchem search. 
It is a part of the old code, but wasn't part of the core-spec2vec functionality and hence was never beyond first prototyping --> in need of quite some refactoring! (however, I believe it can be quite a powerful functionality to improve, or check metadata)
--> issue #146 
- More sophisticated peak filter function. ``select_by_relative_intensity`` leaves too many spectrums with too many remaining peaks.

**Comment by jspaaks** [comment]
This made me really happy, thank you!

**Comment by florian-huber** [comment]
**With the current version of the code (PR #187 ) I am able to run the entire pre-processing pipeline on all 147,000 spectra!**

The only custom extension (i.e. not code from matchms) is the part where I add/correct metadata by PubChem lookups. This should probably anyway not become core functionality of matchms. At least not right now.

To test the workflow and share it with the collaborators/PI I added a notebook, the additional scripts (careful: scripts, not proper code...) to a separate branch. The notebook can be found here:
https://github.com/matchms/matchms/blob/dev-iomega-workflow/notebooks/iomega-workflow-1-from_mgf_to_cleaned_data.ipynb

In my opinion this issue can be closed.

**Comment by florian-huber** [comment]
I close this because in my view the essential pre-processing part is in place and working nicely.
