### ISSUE TITLE
spec2vec weighting of words by peak intensity

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms-backup#142]
Maybe the vector of weights should be scaled such that it sums to unity.

**Comment by florian-huber** [comment]
The weighing is now added in PR #165 .
I haven't decided on the normalization of weights yet. For the Spec2Vec similarity score it will not make a difference since that is a cosine score (and hence only cares about the angle between spectrum vectors, not their length).

**Comment by jspaaks** [comment]
But the angle changes with length of the elements of the vector, right? For a 2 dimensional vector ``[1,10]``the angle will be different than for ``[1,100]``?

**Comment by florian-huber** [comment]
In the spectrum vector the words do not represent separate dimensions as in your example. It is rather that every word is placed somewhere in the _size_-dimensional space according to word2vec. The spectrum is then the sum of all word vectors. 
To account for the fact that some words are more important than others, we weigh them based on their peak intensity, a bit like this: ``spectrum_vector = sum([weights[i]* word_vectors[i] for i in range(number_words)])``.

If I change the weights to a sum of 1, I would only rescale all word vectors by ``/np.sum(weights)``, so it is more like going from ``[1,10]`` to ``[2,20]``.

**By the way:** 
In the original code we took the **sum** of all weighted word vectors. In the current implementation it is the **mean**. If we stick to the "only the orientation matters" standpoint than we could also normalize the vector as a whole (to length unity). 
However, in NLP (where this idea comes from) people define a "centroid vectors" by using the **sum**, so it feels best to stick to that --> added it to PR #165

**Comment by florian-huber** [comment]
The weighing of words by peak intensity was added as part of #183 .
