### ISSUE TITLE
Publish Conda package 

### ISSUE THREAD

**Issue by fdiblen** [matchms/matchms-backup#15]
Create a Conda organisation and publish it there.

**Comment by cwmeijer** [comment]
blocked #14

**Comment by fdiblen** [comment]
Conda-forge has a guide here:
https://conda-forge.org/docs/maintainer/adding_pkgs.html

**Comment by jspaaks** [comment]
This issue can be closed when https://github.com/matchms/matchms/pull/68 is merged.
