### ISSUE TITLE
Switch to scipy array based similarity score for Spec2Vec similarity calculation.

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms-backup#163]
The current implementation of calculating Spec2Vec similarity scores is based on pairwise calculations. That involves a lot of Python looping which makes it very slow (touching on #74 here).
The difference to using scipy for calculating cosine scores between many spectrums at once is quite drastic.

When I run code based on what I mentioned in #162, the current method looks like this:
```python
queries = documents[:500]
similarities = calculate_scores(queries, queries, spec2vec).scores
```
In the original ("old") code I was first calculating the spectrum/document vectors and than calculating all similarities at once, like this:

```python
from scipy import spatial

queries = documents[:500]
spec_vectors = np.array([spec2vec.calc_vector(doc) for doc in queries])
similarities = 1 - spatial.distance.cdist(spec_vectors, spec_vectors, 'cosine')
```
### Quite drastic run time difference
When running the above code, the second version was about **1000 times faster.** 

I had to change the Spec2Vec class though, to allow calculating document vectors separately (changes were only made locally).
```python
class Spec2Vec:

    def __init__(self, model=None, documents=None):
        self.model = model
        self.dictionary = gensim.corpora.Dictionary([d.words for d in documents])

    def __call__(self, query, reference):
        query_vector = self.calc_vector(query)
        reference_vector = self.calc_vector(reference)
        cdist = scipy.spatial.distance.cosine(query_vector, reference_vector)

        return 1 - cdist

    def calc_vector(self, document):
        """Derive latent space vector for entire document."""
        bag_of_words = self.dictionary.doc2bow(document.words)
        words = [self.dictionary[item[0]] for item in bag_of_words]
        word_vectors = self.model.wv[words]

        return numpy.mean(word_vectors, 0)
```

**Comment by HannoSpreeuw** [comment]
@florian-huber 1000 times faster is quite impressive. We should take it on. Would you like me to submit a PR for these changes?

**Comment by florian-huber** [comment]
Sounds good Hanno! What do you think @jspaaks (since we discussed this before)?
