### ISSUE TITLE
Code coverage not being recorded by sonarcloud

### ISSUE THREAD

**Issue by sverhoeven** [matchms/matchms-backup#168]
On https://sonarcloud.io/dashboard?id=matchms_matchms the coverage is set to 0%.

In the log of a GH Action it says:

```
INFO: Python test coverage
INFO: Parsing report '/github/workspace/coverage.xml'
WARN: Invalid directory path in 'source' element: /home/runner/work/matchms/matchms/matchms
ERROR: Cannot resolve the file path 'Scores.py' of the coverage report, the file does not exist in all <source>.
ERROR: Cannot resolve 42 file paths, ignoring coverage measures for those files
INFO: Sensor Cobertura Sensor for Python coverage [python] (done) | time=43ms
```

**Comment by sverhoeven** [comment]
For example GH action job https://github.com/matchms/matchms/runs/625682096?check_suite_focus=true

**Comment by sverhoeven** [comment]
I ran analyis on my pc, which corrected the coverage in master branch, but I want the GH action to record the coverage.

**Comment by jspaaks** [comment]
I tried to make you an admin on ~~https://github.com/citation-file-format/cff-converter-python~~ https://sonarcloud.io/dashboard?id=citation-file-format_cff-converter-python. Not sure it worked, but might be useful for comparison.

**Comment by sverhoeven** [comment]
After PR #169 was merged the https://sonarcloud.io/dashboard?id=matchms_matchms shows coverage again
