### ISSUE TITLE
Add tests for Document and SpectrumDocument classes

### ISSUE THREAD

**Issue by fdiblen** [matchms/matchms-backup#170]
We need to add tests for every method in

- [x] matchms/similarity/spec2vec/Document.py
- [x] matchms/similarity/spec2vec/SpectrumDocument.py

**Comment by jspaaks** [comment]
https://github.com/matchms/matchms/pull/160/commits/1c7e0ec2f2d16a4379a4b30d9c45227c2fb38b21
