### ISSUE TITLE
Openbabel based derive_smiles_from_inchi breaks with incorrect inchi

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms-backup#171]
I ran the metadata cleaning filters on the entire GNPS dataset (the mgf I provided), see #142.
The ``derive_smiles_from_inchi`` failed badly and it turned out that this happened whenever it received and inchi that was actually a smiles or an inchikey.

While it would be good to not have ``derive_smiles_from_inchi`` crash at all (not matter what the input is), I probably will first focus on getting the metadata right, which means:
- add more sever removal of smiles to ``clean_inchis``
- add inchikey detection and removal to ``clean_inchis``

**Comment by jspaaks** [comment]
See also #187

**Comment by florian-huber** [comment]
This was actually solved with the more thorough cleaning as implemented in #181 and the more thorough testing function ``is_valid_inchi``.
