### ISSUE TITLE
setup autogenerating developer documentation

### ISSUE THREAD

**Issue by fdiblen** [matchms/matchms-backup#18]

**Comment by fdiblen** [comment]
It would be nice to add an updated version of the flowchart of spec2vec.

See [code_flowchart.pdf](https://github.com/NLeSC/spec2vec/files/4354062/code_flowchart.pdf)

**Comment by CunliangGeng** [comment]
I created a demo for documentation. Before I make more efforts, could you have a look at the demo?  @florian-huber  @fdiblen @HannoSpreeuw @jspaaks @sverhoeven  

To check the demo, you need to download the file and open `doc/html/index.html`.
[doc.zip](https://github.com/matchms/matchms/files/4388777/doc.zip)

**Comment by HannoSpreeuw** [comment]
Looks very nice.

`Module Index` does not seem to work.

**Comment by jspaaks** [comment]
Very nice

**Comment by CunliangGeng** [comment]
@HannoSpreeuw @fdiblen  Thanks, I'll fix the `Module Index` problem.

**Comment by fdiblen** [comment]
Can we sign up for matchms on readthedocs?

**Comment by CunliangGeng** [comment]
We need a team account to do that :-)

**Comment by CunliangGeng** [comment]
@fdiblen  I registered readthedocs with the team email, which needs the admin to verify it. The user name and password can be found in lastpass (by searching `readthedoc`)

**Comment by jspaaks** [comment]
We can configure this project such that readthedocs knows where to find the sphinx api docs using a setup similar to https://github.com/xenon-middleware/xenon-tutorial/blob/master/.readthedocs.yml

**Comment by CunliangGeng** [comment]
PR #61

**Comment by CunliangGeng** [comment]
> We can configure this project such that readthedocs knows where to find the sphinx api docs using a setup similar to https://github.com/xenon-middleware/xenon-tutorial/blob/master/.readthedocs.yml

@jspaaks  Readthedocs can automatically detect the `docs` when importing this repo on its website.

**Comment by HannoSpreeuw** [comment]
Nice, well done. I will now close this.
