### ISSUE TITLE
Add rdkit to environment (if possible)

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms-backup#182]
Rdkit is currently not part of the environment.

The former spec2vec code uses ``openbabel`` and ``rdkit``, both of which can be a bit troublesome to import. Furthermore openbabel has a serious license issue (--> #129).
In principle, both packages have a lot of redundant functionality. However, in practice they have different pro's and con's (purely speaking in terms of their output). So far I have used openbabel for conversions between inchi and smiles, and for checking if those are correct (it is able to read and handle a larger number of those correctly). In PR #181 I tried to implement the checking part using rdkit despite a little lower retrieval rate.  

Rdkit before was used for 2 things: 
- One (essential) part is to derive **molecular fingerprints** from smiles. Those are used to calculate actual molecular similarities.
- The other case was using rdkit to plot molecules.

What do you think? Can we add rdkit to the environments?

**Comment by jspaaks** [comment]
I propose we first sort out the existing licensing issues https://app.fossa.com/projects/git%2Bgithub.com%2Fmatchms%2Fmatchms/refs/branch/master before piling on more pain

**Comment by florian-huber** [comment]
Ok. Looks like a nice mess. Let me know if I can help with anything.

**Comment by florian-huber** [comment]
Closed by PR #181 .
