### ISSUE TITLE
consistent numpy usage

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms-backup#186]
1. ``import numpy``
1. ``import numpy as np``
1. ``from numpy import asarray, hstack, sum`` etc

We chose to go with option 1

**Comment by jspaaks** [comment]
PR #191

**Comment by sverhoeven** [comment]
Why not option 2, this what numpy themselves use in their docs?

**Comment by jspaaks** [comment]
I guess it's an arbitrary choice. ``np`` is not much shorter than ``numpy``, but it is slightly less clear.

**Comment by cwmeijer** [comment]
I would vote for option 2 because that's what many people use, but if this was decided earlier to go for option 1 then I don't want to resurrect this discussion ;-)
