### ISSUE TITLE
create a cli

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms-backup#29]

**Comment by fdiblen** [comment]
We want to have a command line tool to process the files.
example:
`matchms --file dataFile --filterX1 --filterX2 --interactive --export exportFile`

Click and argparse can be used that but there are many more options.
https://docs.python.org/3/library/argparse.html
https://click.palletsprojects.com/en/7.x/

**Comment by HannoSpreeuw** [comment]
But which fuctionality do we want to support?
Do we want to support every function from matchms?

**Comment by jspaaks** [comment]
Before we do a lot of work, can we backtrack for just a moment and evaluate why we wanted this? I think the answer was "KNIME node", and if so we should discuss how to design for that use case.

**Comment by sverhoeven** [comment]
For KNIME we can use KNIME Python nodes (like https://hub.knime.com/knime/extensions/org.knime.features.python2/latest/org.knime.python2.nodes.script.Python2ScriptNodeFactory) or the https://github.com/3D-e-Chem/knime-python-node-archetype

**Comment by jspaaks** [comment]
After some discussion, we decided to close this issue, because it was originally added as a step towards disseminating matchms as a KNIME node, but we have postponed that until at least after https://github.com/matchms/matchms/issues/20. If we find some potential users for having matchms as a KNIME node later, we can make a new issue that (possibly) includes making a cli.
