### ISSUE TITLE
identify generic and project specific parts

### ISSUE THREAD

**Issue by fdiblen** [matchms/matchms-backup#3]
We need to identify project specific parts and generic parts of the software.

- Separate generic from specific. 
- Separating data handling from algorithmic code. 
- Discuss first before Florian for the actual refactoring: i.e. separating generic and specific code.
 
Specific here means either for mass spectra or genes. It should be entered into a library.

**Comment by fdiblen** [comment]
There is a flowchart made by @florian-huber [code_flowchart.pdf](https://github.com/NLeSC/spec2vec/files/4354062/code_flowchart.pdf)

**Comment by HannoSpreeuw** [comment]
Closely connected to #7 
We will merge these issues.

**Comment by CunliangGeng** [comment]
comments have been moved to #7. Close this issue now.
