### ISSUE TITLE
Fix openbabel

### ISSUE THREAD

**Issue by fdiblen** [matchms/matchms-backup#31]
Openbabel is disabled in requirements.txt nd it was needed by spec2vec.
However, pypi package of version 3.0.0 is only available for windows.
https://pypi.org/project/openbabel/3.0.0/#files

Also, only the development version (20.04) of ubuntu has openbabel 3.0.0. Github actions doesn't have the latest version of Ubuntu. They only have LTS versions.

To do:
- [x] check if we can find a proper way to install it
- [x] fix requirements.txt
- [x] fix CI if it is failing due to this issue 
- [x] add openbabel dependency to the documentation

**Comment by jspaaks** [comment]
Additionally, it looks like you need to install openbabel and libopenbabel-dev
```
sudo apt install openbabel
sudo apt install libopenbabel-dev
```
Let's confirm that this is in fact correct, then add that to the readme

**Comment by HannoSpreeuw** [comment]
So did anyone just try 
`pipenv shell`
`pipenv install .`
?
That took 15 minutes on my desktop, but it worked.
Manjaro Linux 19.x.y.

**Comment by fdiblen** [comment]
@HannoSpreeuw Did you run the Jupyter notebooks?
Btw, this is not the right issue to discuss the building process. Let's chat in teams when you have time.

**Comment by CunliangGeng** [comment]
check #34 for the updated 'requirement.txt'.

It should be fine not to specify the version when you try to install dependencies, because the versions are fetched from pypi automatically.

I tired to install the dependencies on MAC, and I have to use `conda install name -c conda-forge` to install these two packages: `openbabel==3.0.0` and `rdkit`.  For all the other packages, pip works well even with specifying the version.

**Comment by fdiblen** [comment]
@CunliangGeng Thank you for checking this. We intentionally fix the versions for reproducibilit e.g. if someone has a problem, it becomes easier to debug it.

What other dependencies do we need to add? Are you sure these extra packages are not dependencies of dependencies?

I can confirm that conda-forge has openbabel 3.0.0 package.
See: https://github.com/conda-forge/openbabel-feedstock

That probably means we need to use openbabel conda package while building.
@florian-huber Do you have any comments on this?

**Comment by HannoSpreeuw** [comment]
@fdiblen We (@CunliangGeng and me) have been trying to run the first notebook.
Until now I have not been able to do a succesful import of the first module I encountered - MS_functions.py.
The details of this problem I will not share here.

**Comment by fdiblen** [comment]
We now install openbabel using anaconda. Github Actions is also using anaconda when building. (PR #28 ) The dependencies are in environment.yml.

**Comment by CunliangGeng** [comment]
The Github Actions passed, closing this issue.

**Comment by fdiblen** [comment]
Two of the checks of this issue are still pending.

**Comment by jspaaks** [comment]
@fdiblen I agree with @CunliangGeng that we can close this issue. The 4 checks at the top assume that we are installing from PyPI, which we decided we would abandon for the time being, in favor of installing from conda. In my opinion, this nullifies elements 2 and 4 from the checklist above. What do you think?

**Comment by fdiblen** [comment]
We now have a proper environment.yml and conda package that solves this issue.
