### ISSUE TITLE
Fix linting

### ISSUE THREAD

**Issue by fdiblen** [matchms/matchms-backup#32]
Linting is temporarily disabled in Github actions.
It should be fixed after #28 is merged.

**Comment by CunliangGeng** [comment]
The source code does not conform to the official Python style
guide (PEP8), see https://www.python.org/dev/peps/pep-0008

Need to fix the style problem with following guide:

- Run `pip install --upgrade yapf` to install the latest version of yapf.
- Run `yapf -i yourfile.py` to automatically fix most errors.
- Run `yapf -d yourfile.py` to preview what would be changed.
- uncomment the `assert` in `tests/test_lint.py` 
- run the `tests/test_lint.py` to see if the style pass or not

**Comment by jspaaks** [comment]
strictly speaking we said we would be using prospector (which includes pep8, apparently)

Prospector has 1404 messages btw :)

**Comment by jspaaks** [comment]
OK, so I followed @CunliangGeng 's suggestion. We went from 1404 errors to about 200. Yay. I made a PR BTW: #45

**Comment by CunliangGeng** [comment]
I copied the suggestions from our `python template` :-) We can of course change that if necessary.

**Comment by jspaaks** [comment]
Corrected some more errors, now down to 166 (excluding ``tests/``).

**Comment by jspaaks** [comment]
~~PR #45 ~~ We decided to merge some of Florian's more recent changes, but this undid some of the work from #45. See also #50.

**Comment by jspaaks** [comment]
This issue should be closed.
