### ISSUE TITLE
Check dependencies and update requirements.txt

### ISSUE THREAD

**Issue by CunliangGeng** [matchms/matchms-backup#34]
The original `requirements.txt` does not contail all packages needed. Need to check the dependencies and update the `requirements.txt`.

**Comment by HannoSpreeuw** [comment]
Does pipenv circumvent this issue?

As I mentioned on Slack,
```
pipenv shell
pipenv install .
```
worked for me, although it took quite long, 15 minutes.

But perhaps you already tried that.

**Comment by CunliangGeng** [comment]
No, I did not try `pipenv`,  it's new to me.

**Comment by HannoSpreeuw** [comment]
Okay, then you probably need to do a
`pip install pipenv` first.

**Comment by jspaaks** [comment]
PR #35
