### ISSUE TITLE
add types

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms-backup#37]
At least to user-facing part of the library.

And use [pytest-mypy](https://pypi.org/project/pytest-mypy/) for continuous type checking  (thanks @LourensVeen for the tip)

**Comment by cwmeijer** [comment]
This issue is marked for needing discussion but it has a PR already... Simple comment anyway:
Yay type checking! I never used it but have been planning to. User facing API is a great place to start!

**Comment by jspaaks** [comment]
The ``needs_discussion`` label was added March 23 though.

**Comment by LourensVeen** [comment]
When you start using pytest-mypy, you'll probably see some error messages related to libraries that don't have type annotations. See https://github.com/yatiml/yatiml/blob/develop/setup.cfg for an example of how to configure it to ignore those libraries. I'm using `pytest-mypy>=0.4.0` there to avoid a compatibility issue with recent versions of mypy, you may want to do the same. Also, don't forget to add a ``py.typed`` file (see https://www.python.org/dev/peps/pep-0561/).

I'm happy to help if you get stuck somewhere, just let me know.

**Comment by jspaaks** [comment]
PR #154
