### ISSUE TITLE
Figure out how the Python package should be structured

### ISSUE THREAD

**Issue by fdiblen** [matchms/matchms-backup#39]
Work in branch https://github.com/matchms/matchms/tree/old-code-new-location

**Comment by CunliangGeng** [comment]
The practices are:
1. use relative import for internal code, see d5bc64fb61437f9aaa34b6321d4ce2a91b2cb458
2. expose most common packages/modules/functions and remove unnecessary ones in `__init__.py` adc2bd3d3e7d4448c88c0b83768585739414e3c6

You could see the examples in the two commits.

**Comment by CunliangGeng** [comment]
Now you can successfuly `import matchms` and see the exposed modules/functions `dir(matchms)`.
