### ISSUE TITLE
Update and add unit tests

### ISSUE THREAD

**Issue by fdiblen** [matchms/matchms-backup#4]
Add unit tests to the generic parts of the software.

**Comment by fdiblen** [comment]
There is a test task in Github actions. At the moment it is disabled but it should be updated after adding proper tests.

**Comment by florian-huber** [comment]
I added a branch with "issue4_..." with test data (MGF file) and a first script to execute some of the core functions. This could hopefully be used to turn it into tests.

**Comment by CunliangGeng** [comment]
All existing test cases failed, need check and clean those tests.

**Comment by cwmeijer** [comment]
Just adding some information after talking to Florian:
According to Florian, tests in matchms/tests/ are testing bigger functionalities so are sort of in between a unit and integration test.
The test that has the widest scope right now, and is, therefore, most like an actual integration test is in matchms/tests/test_similarity_measures.py. This test reads data, then trains a model and calculates similarities between data points. It does not test looking up most similar data yet.

**Comment by jspaaks** [comment]
Can we change the title such that we know when this issue is done? Currently it's rather open ended.

**Comment by cwmeijer** [comment]
this issue is too broad and can therefore never be finished. there are tests in place however so we're closing this for now. we'll do analysis for coverage later.
