### ISSUE TITLE
Fix tests of new code

### ISSUE THREAD

**Issue by fdiblen** [matchms/matchms-backup#40]
Tests of the new code are failing. 
See https://github.com/matchms/matchms/runs/533723732?check_suite_focus=true

**Comment by CunliangGeng** [comment]
I had a look at the test scripts and would skip these tests to solve this issue currently.
We need to create more issues to 
1. check, clean and format existing test cases before adding new tests in #4, which first needs a systematic design of tests.
2. format all source code based on pep8

**Comment by CunliangGeng** [comment]
PR #42

**Comment by fdiblen** [comment]
@CunliangGeng thanks! Can you create an issue about linting?

**Comment by CunliangGeng** [comment]
What is the #32 about?

**Comment by fdiblen** [comment]
Sorry, missed it. Could you update the issue to add some extra details (e.g. doing it in tests)?

**Comment by CunliangGeng** [comment]
Updated #32 and #4. The issue can be closed now.
