### ISSUE TITLE
import MS_functions gives error

### ISSUE THREAD

**Issue by HannoSpreeuw** [matchms/matchms-backup#44]
Using the matchms master branch, commit 50a1e9c bf56fd1.
Date:   Thu Mar 26 11:03:50 2020 +0100.

`conda env create -f environment.yml`
`conda activate matchms`
`cd ../notebooks/`
`jupyter notebook`

Open the first notebook, run the first code block. Below you can see the result:

![image](https://user-images.githubusercontent.com/11661087/77660781-0ba0c400-6f7a-11ea-8230-4335487c00f7.png)

**Comment by fdiblen** [comment]
`from matchms import MS_functions` should work.

**Comment by jspaaks** [comment]
I had some trouble with getting this to work in a notebook. In the end, I added ``conda install nb_conda`` while having the ``matchms`` conda environment activated (not sure that matters, but ok). This gave me an extra tab labeled 'Conda' in the notebook. After that I was able to import matchms and whatever was in it.

Maybe we should state this somewhere in the docs, or add it to the environment.yml?
Also, I didn't have a locally installed jupyter notebook, so I did 
```
sudo apt install jupyter-core
```

but it turns out you also need 
```
sudo apt install jupyter-notebook
```
otherwise jupyter does not recognize its own subcommand ``notebook``.

**Comment by HannoSpreeuw** [comment]
Okay @jspaaks, I'll try your suggestions in a minute.

Anyway, replacing 
`from . import helper_functions as functions`
by 
`import helper_functions as functions`
results in 
```
---> 21 from scipy import spatial
     22 import json
     23 import math

ModuleNotFoundError: No module named 'scipy'
```

This seems weird, since
`python -c "import scipy"`
works after
`conda activate matchms`.

**Comment by HannoSpreeuw** [comment]
@fdiblen 
Modifying that line in the notebook, as you suggested:
`from matchms import MS_functions`
results in the same error:
```
---> 21 from scipy import spatial
     22 import json
     23 import math

ModuleNotFoundError: No module named 'scipy'
```

**Comment by HannoSpreeuw** [comment]
@jspaaks Your suggestion
`conda install nb_conda`
made it work, after modifying the import statement in the notebook, as suggested by @fdiblen.
The import statement in the code need not be modified, just the notebook.

Thanks! I will branch off master in the notebook repo and submit a PR.

**Comment by fdiblen** [comment]
I have just checked and it works for me. @HannoSpreeuw What will you create a PR for? We already have #30 and https://github.com/matchms/notebooks/pull/5

This is what I did to test:
When you create a new environment, jupyter is not installed by default.
You can install jupyterlab (improved version of jupyter notebook: sort of IDE):
`conda install jupyterlab `
Start:
`jupyter-lab`

**Comment by HannoSpreeuw** [comment]
It is just a PR for a fix in the notebooks repo.
I submitted this PR.

**Comment by fdiblen** [comment]
@HannoSpreeuw We can close this, right?

**Comment by HannoSpreeuw** [comment]
Yes
