### ISSUE TITLE
Uniform and fix docstring style

### ISSUE THREAD

**Issue by CunliangGeng** [matchms/matchms-backup#46]
The code uses a combination of [Numpy](https://www.sphinx-doc.org/en/master/usage/extensions/example_numpy.html#example-numpy) and [Google](https://www.sphinx-doc.org/en/master/usage/extensions/example_google.html) docstring styles. 

- [x]  Question: which one do we use? Numpy!
- [ ] check if there is docstring formatter tool
- [ ] fix and format the docstring style

**Comment by jspaaks** [comment]
(after 5 minutes browsing those links)
I don't think they are really different in what they can do, are they? I'd be totally fine with you just picking one.

**Comment by CunliangGeng** [comment]
No difference on effects, just different personal tastes. I'd keep it to Numpy considering the code use it more :-)

**Comment by jspaaks** [comment]
It is hereby decided! :)

**Comment by CunliangGeng** [comment]
@florian-huber @jspaaks @sverhoeven @fdiblen @HannoSpreeuw 
Reminder: We have decided to use [Numpy](https://www.sphinx-doc.org/en/master/usage/extensions/example_numpy.html#example-numpy) docstring style, please use this style when you refactor the code.

**Comment by CunliangGeng** [comment]
Close this issue because the source code is going to be refactored.
