### ISSUE TITLE
Importing/exporting word2vec models fails.

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms-backup#48]
Make sure importing/exporting word2vec models works across different environments.
It seems to often fail when models are trained and saved in one environment and are being imported from another one! 
- Check how GENSIM exports the models and look for alternative way to store the model (e.g. in other format).
- For right now: I commented out the model importing test.

**Comment by fdiblen** [comment]
@florian-huber Can you explain what you mean with environment? 
I can think of:
- Python virtual environment (including conda)
- Python environment with different versions of dependencies installed
- Different OS

**Comment by florian-huber** [comment]
Didn't do enough testing to really tell exactly. But I would assume it's the second, different versions of dependencies.

**Comment by cwmeijer** [comment]
these bugs are in features that are not in matchms. this issue should be in an another repo.
closing
note that you can transfer this issue with a button on the right
