### ISSUE TITLE
Add importing/load_from_mgf function

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms-backup#51]
- [ ] implement ``load_from_file()``:

    take an mgf file, load it, return array of ``Spectrum``. I think we can limit a ``Spectrum`` to include only the M/z ``float[]``, the intensity ``float[]``, and the metadata ``dict``. I think the class does not need any of the other stuff like ``max_frag``, ``merge_energies`` and what have you. Therefore, I expect that the easiest way to do this, is to simply delegate parsing of the mgf to ``pyteomics`` like @florian-huber is also doing. It's worth looking into whether we can simply use pyteomics's Spectrum class directly, or inherit from it (https://pyteomics.readthedocs.io/en/latest/api/mgf.html#mgf-read-and-write-ms-ms-data-in-mascot-generic-format).
- [ ] add tests for ``load_from_file``

**Comment by jspaaks** [comment]
See also:
- step 1 in this notebook https://github.com/matchms/notebooks/blob/9a8f94db0250c2cc540b83de87147c08fac34187/tutorial.ipynb and
- my comment https://github.com/matchms/notebooks/pull/12#issue-395224959.

**Comment by sverhoeven** [comment]
* So metadata dict would contain things like precursor mass, parent mass, smiles, inchikey, charge right?

**Comment by jspaaks** [comment]
>     * So metadata dict would contain things like precursor mass, parent mass, smiles, inchikey, charge right?

correct

**Comment by florian-huber** [comment]
Agree with @jspaaks, Spectrum class could in principle be reduced to just this: peaks, peak intensities and metadata (as described by Stefan).

**Comment by jspaaks** [comment]
This is part of https://github.com/matchms/matchms/pull/67. Once that is merged, this issue should be closed.
