### ISSUE TITLE
add filtering/roundoff_mz function

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms-backup#53]
- [ ] add simplest of harmonization methods to harmonization/, maybe as simple as rounding off the M/z values to a predefined precision (this is similar but not equal to @florian-huber's ``Spectrum.merge_energies``). 

    The interface could be:

    ```
    spectrum = roundoff_mz(spectrum, precision=None)
    ```

- [ ] add tests for the ``roundoff_mz()`` harmonization function

**Comment by jspaaks** [comment]
Hi @florian-huber:
I intended this as a simple toy function, but since we now have a couple of real examples, maybe we do not need it anymore?

**Comment by florian-huber** [comment]
Yes @jspaaks, this is less important than what we already have in #67 (and might also be implemented differently in the end...), so let's close this issue for now.
