### ISSUE TITLE
move word2vec related functionality to new function files under similarity/word2vec/

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms-backup#57]
For the moment, I think we should integrally remove any functions that mention any Word2Vec related terms such as: 
- ``model``
- ``document``
- ``corpus``
- ``corpus_weights``
- ``stop_word``
- ``idf_score``
- ``vocabulary``
- ``vectorize``
- ``Word2Vec``
- topic modeling
- ``sentences``
- ``gensim``

And move them to ``similarity/word2vec/`` for the time being.

Each function should be in its own file, with the file name exactly equal to the function name.

Once this is done, we can start a discussion on whether these functions should stay under ``similarity/word2vec``, or be moved to their own repository, perhaps even https://github.com/matchms/spec2vec ?

**Comment by jspaaks** [comment]
TODO @jspaaks: lay out conceptual workflow with @florian-huber, something like:

- for all spectrums, convert a spectrum to a sentence (1 spectrum -> 1 sentence)
- all sentences represent a corpus (?)
- based on the corpus, train a model using gensim
- the model serves as an input argument for the (as yet unnamed) similarity function, I guess it could be called "spec2vec", so a user can do:

```python
from matchms.harmonization import harmfun1, harmfun2 
from matchms.similarity import simfun1, simfun2, simfun3
from spec2vec import simfun4
from matchms import Scores, Spectrum

# get spectrum Spectrum from somewhere
# get reference_spectrums Spectrum[] from somewhere

scores = Scores(spectrum=spectrum, reference_spectrums=reference_spectrums)
scores.add_harmonization_function(harmfun1, harmfun2)
scores.add_similarity_function(simfun1, simfun2, simfun3, simfun4) 
scores.calculate()
```

spec2vec module should not include:

- anything to do with cleaning the spectrums / harmonization
- anything to do with networks
- anything to do with plotting
- anything to do with library search / lookup
- anything to do with classical similarity scores

**Comment by florian-huber** [comment]
This structure looks really good and would allow to separate the non-MS specific parts from the MS parts!
And indeed the workflow looks mostly like @jspaaks described above:

- convert all spectra to sentences (lists of strings). 
This could either be part of **matchms** export or part of **Spec2Vec** import.
- all sentences together form the 'corpus'
- gensim word2vec model is trained on the corpus (or: pre-trained model is imported!)
- spectra vectors are calculated (using word vectors/word embeddings from the trained word2vec model AND the spectra intensity values for weighting each word vector).
- calculating a 'spec2vec similarity' using the generated spectra vectors.

Input needed: Query spectra, reference spectra, model parameters OR pre-trained model.
Outputs: similarity matrix.

**Comment by jspaaks** [comment]
And the size of the resulting similarity matrix is 1 column by _n_ rows, with _n_ the number of reference spectrums?

**Comment by jspaaks** [comment]
PR https://github.com/matchms/matchms/pull/71 has a directory ``similarity/spec2vec/`` with all spec2vec related functions (or rather all non-spec2vec related functionality has been removed).

More importantly, the PR also lays out the basic structure of making a model (``similarity/spec2vec/make_model.py``), and of a Spec2Vec similarity function (``similarity/spec2vec/similarity/Spec2Vec.py``). The proposed structure is much simpler than what we had before. With this strucutre, a user can do more or less this:

(note this snippet assumes spec2vec has been made available as its own package):


```python
import os
from matchms.importing import load_from_mgf
from matchms.filtering import filterfun1, filterfun2
from matchms import calculate_scores
from spec2vec import make_model
from spec2vec.similarity import Spec2Vec


def test_user_workflow():

    def apply_filters(s):
        filterfun1(s)
        filterfun2(s)

    # loading
    references_file = 'pesticides.mgf'

    reference_spectrums_raw = load_from_mgf(references_file)
    reference_spectrums = [s.clone() for s in reference_spectrums_raw]

    query_spectrum_raw = reference_spectrums_raw[0]
    query_spectrum = query_spectrum_raw.clone()

    # filtering
    for s in reference_spectrums:
        apply_filters(s)

    apply_filters(query_spectrum)

    # make a model
    model = make_model(reference_spectrums)

    # define similarity functions
    similarity_functions = [Spec2Vec(model)]

    # calculate_scores
    scores = calculate_scores(query_spectrum,
                              reference_spectrums,
                              similarity_functions)

    print(scores)


if __name__ == '__main__':
    test_user_workflow()
```

**Comment by fdiblen** [comment]
As #71 was merged, we can close this issue, right?

**Comment by jspaaks** [comment]
Yes issue can be closed
