### ISSUE TITLE
implement Spectrum

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms-backup#63]
see discussion in https://github.com/matchms/matchms/issues/41#issuecomment-607092161

We agreed during the discussion that ``matchm.Spectrum`` should not inherit from ``pyteomics.Spectrum``, but rather use composition. I assume that means ``matchms.Spectrum`` is instantiated as follows:
```python
spectrum matchms.Spectrum = Spectrum(spectrum pyteomics.Spectrum)
```
To confuse (the inside of) ``Spectrum`` even more, ``Spectrum``'s ``.plot`` method should use ``spectrum_utils.MsmsSpectrum.plot()`` (see snippet 1 here https://github.com/matchms/notebooks/blob/9a8f94db0250c2cc540b83de87147c08fac34187/tutorial.ipynb).

By having the confusing part on the inside of the class, the user-facing side of ``matchms.Spectrum`` can stay clean and tidy.

**Comment by florian-huber** [comment]
If that is not conflicting with anyone, I would start working on the newly structured code starting with this issue.
I would start a new branch for drafting the Spectrum class (and let you know when I have time to work on it to see if we can do some pair programming) ?

**Comment by jspaaks** [comment]
Probably something like this (untested, beware):

```python
# file: matchms/Spectrum.py

from spectrum_utils.spectrum import MsmsSpectrum
from spectrum_utils.plot import spectrum as plot

class Spectrum:

    def __init__(self, pyteomics_spectrum):
	self.pyteomics_spectrum = pyteomics_spectrum
        self.mz = pyteomics_spectrum["m/z array"]
        self.intensities = pyteomics_spectrum["intensity array"]
        self.something_from_the_metadata = pyteomics_spectrum["metadata"]["something_from_the_metadata"]

    def plot(self):
        
        s = MsmsSpectrum(identifier=None,
                         precursor_mz=None,
                         precursor_charge=None,
                         mz=self.mz, intensity=self.intensities)
        plot(s)

```

**Comment by jspaaks** [comment]
In progress
- https://github.com/matchms/matchms/pull/66
- https://github.com/matchms/notebooks/pull/13

**Comment by jspaaks** [comment]
(Note I ended up with a slightly different constructor that what was discussed at the top of this issue.)

This is part of https://github.com/matchms/matchms/pull/67. Once that is merged, this issue should be closed.
