### ISSUE TITLE
Check package version string 

### ISSUE THREAD

**Issue by fdiblen** [matchms/matchms-backup#69]
We can check if all the version strings are the same.
See below link for an example.

https://github.com/citation-file-format/cff-converter-python/blob/master/test/test_consistent_versioning.py

**Comment by sverhoeven** [comment]
Maybe use https://github.com/c4urself/bump2version aswell.

**Comment by HannoSpreeuw** [comment]
I am not sure I understand this issue. 
Do the Spec2Vec source code files contain version strings that were inserted manually?

**Comment by fdiblen** [comment]
@HannoSpreeuw Yes, in a few files. They all should have the same version when we make a new release.

**Comment by fdiblen** [comment]
> Maybe use https://github.com/c4urself/bump2version aswell.

Looks like a good option.

**Comment by HannoSpreeuw** [comment]
There are a lot of occurrences of version strings in the matchms repo,
`grep -rniI . -e "__version__ =" | wc -l` gives `53`.

**Comment by HannoSpreeuw** [comment]
But all of these "hits" are in the .eggs directory and unrelated to matchms.
Except this one:
`./matchms/__version__.py:1:__version__ = '0.1.0'`.

**Comment by jspaaks** [comment]
the .eggs directory is generated and is not checked into the repo --ignore it

**Comment by fdiblen** [comment]
To close this issue do:

- [ ] Check all the files with version string in it and use bump2version to have the same version
- [ ] add a test and verify versions from all the files during the build using [this](https://github.com/citation-file-format/cff-converter-python/blob/master/test/test_consistent_versioning.py)

**Comment by HannoSpreeuw** [comment]
> the .eggs directory is generated and is not checked into the repo --ignore it

But I think this means that we don't have a problem to solve.

**Comment by HannoSpreeuw** [comment]
Unless we have a also have a different formatting of the version string.
I.e. different from `__version__ =`. 
I tried without the space between `__version__` and `=`, but that gave no hits:
```
grep -rniI . -e "__version__=" | wc -l
0
```

**Comment by jspaaks** [comment]
This issue is more about the part after assignment, not the specific naming of ``__version__``

**Comment by HannoSpreeuw** [comment]
I know. But I can only find one assignment of `__version__` outside the `.eggs` directory.

Or do you mean that, besides assignments of `__version__` there are also assignments of e.g. `version`, so without the underscores?

**Comment by jspaaks** [comment]
A repo can have various places where version strings are used. While developing, it can be difficult to maintain consistency between these places. This issue is about using unit testing to check for each place that we know about. I'm pasting the link to a working example again for your reference:

https://github.com/citation-file-format/cff-converter-python/blob/ee03747b4a4f83ada3f89e460003a6549fcff952/test/test_consistent_versioning.py#L5-L25

In particular, https://github.com/matchms/matchms/blob/f8f3a758179b8aeb74b2be83c177286acc90e7fc/meta.yaml#L5

**Comment by HannoSpreeuw** [comment]
Thanks. 

This, however, does not give me more (hidden?) occurrences of version assignments.
I think that, in fact, this issue can be closed.

```grep -rniI --include \*.py . -e "version" | grep -v ".eggs" | grep -v "conversion"```
gives all occurrences of the string `version` in source files.
and the only one is 
`matchms/__version__.py:1:__version__ = '0.1.0'`

So, with one occurrence only, maintaining consistency is not an issue.

**Comment by jspaaks** [comment]
PR https://github.com/matchms/matchms/pull/185

**Comment by HannoSpreeuw** [comment]
> @HannoSpreeuw Yes, in a few files. They all should have the same version when we make a new release.

@fdiblen which source code files were you referring to?

**Comment by fdiblen** [comment]
Hi @HannoSpreeuw at least these two:
- [ ] matchms/matchms/__version__.py 
- [ ] matchms/meta.yaml

**Comment by HannoSpreeuw** [comment]
I guess you mean `__version__.py`.

Okay, that is where my misunderstanding came from. 
I was thinking about source code files that actually do something, like Spectrum.py, Spikes.py, Scores.py or any other module for importing, exporting, filtering, etc.
But these source code files turn out not to have any version strings inserted manually.

**Comment by fdiblen** [comment]
Yes, `__version__.py`. Underscores are not rendered correctly by Github.
We only have version string for the package but not classes. These strings are used when the packages are published on Pypi, anaconda etc.

**Comment by fdiblen** [comment]
Fixed by #185

**Comment by jspaaks** [comment]
still have to add bump2version notify @cwmeijer

**Comment by cwmeijer** [comment]
we can have bump2version make a commit automatically and tag it. Would we like this features on? Personally I would skip the tagging as I am not used to using them but please comment if you think this is useful.
I like the automatic commit I think but would like some input there as well.
