### ISSUE TITLE
Dimensionality of Scores.scores

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms-backup#72]
The current implementation of ``Scores.scores`` is suitable for problems that satify all of these conditions:
1. have exactly one measured spectrum, 
1. want to query that one spectrum against one or more reference spectrums,
1. according to one or more similarity measures. 

The type of question that people can currently answer is "_I measured a spectrum, what known spectrums exist that are like my measured spectrum_".

I would like to change that functionality a bit such that people can use ``matchms`` for answering an additional, slightly different question, namely: "_I have a library of reference spectrums, and I'd like to know which spectrums are similar_". I think of this as **reference grouping**. This would require ``Scores``'s constructor to be able to take an input argument ``spectrums`` instead of the current ``spectrum``. Since this problem is inherently symmetrical, it would help performance if we could limit evaluation of pairs to one half of the matrix (perhaps by using a new property ``mask``, see discussion on parallel evaluation #74).

Another problem that people can currently not solve, but can be addressed by replacing ``spectrum`` with ``spectrums``, is that of **reference comparison**. For example: "_I have two libraries with reference spectrums, and I'd like to know which spectrum from library1 is similar to which spectrum from library2_".

For simplicity's sake I would propose that we reduce the number of similarity functions to 1 (which serves virtually all use cases).

Happy to hear your thoughts @fdiblen @sverhoeven @florian-huber @HannoSpreeuw @cwmeijer

**Comment by cwmeijer** [comment]
We decided to implement it as jurriaan described above.

**Comment by jspaaks** [comment]
PR https://github.com/matchms/matchms/pull/113

**Comment by jspaaks** [comment]
Defining an env var ``NUMBA_DISABLE_JIT`` as a non zero value could be worth a shot.

(From https://stackoverflow.com/questions/26875191/analyzing-coverage-of-numba-wrapped-functions)

**Comment by florian-huber** [comment]
Thanks a lot! That's a good hint.
Looking that way I found that numba functions can also be run as python functions with ``.py_func``. That way I could run the test on both the compiled and not compiled functions.

[edit] --> seems to do the trick, thanks @jspaaks

**Comment by florian-huber** [comment]
--> Changes added in PR #73 (and for PR #45 )
