### ISSUE TITLE
update workflow figure

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms-backup#78]

**Comment by jspaaks** [comment]
blocked by https://github.com/matchms/matchms/issues/72

**Comment by fdiblen** [comment]
This issue and #72 can also be fixed in next sprint.

**Comment by cwmeijer** [comment]
the workflow is out of sync with what is outlined in #72
jurriaan is the only one who can correct this right now.

**Comment by jspaaks** [comment]
PR https://github.com/matchms/matchms/pull/113
