### ISSUE TITLE
Add Continuous Integration

### ISSUE THREAD

**Issue by fdiblen** [matchms/matchms-backup#8]
Preferably not Travis CI because the future of Travis is not clear.

**Comment by cwmeijer** [comment]
Blocked by https://github.com/NLeSC/python-template/issues/53

**Comment by fdiblen** [comment]
We decided to add CI to matchms first and then to the python-template. This issue is not blocked by https://github.com/NLeSC/python-template/issues/53 anymore.

**Comment by jspaaks** [comment]
PR https://github.com/matchms/matchms/pull/28
