### ISSUE TITLE
Conda install command pins python to 3.7.0

### ISSUE THREAD

**Issue by sverhoeven** [matchms/matchms-backup#84]
Installing matchms via conda with

```shell
conda install -c conda-forge -c bioconda -c nlesc matchms
```

Causes Python 3.7.0 to be installed, trying to upgrade to 3.7.6 with with `conda install -c conda-forge -c bioconda -c nlesc python==3.7.6` causes a package conflict after 15minutes.

I would like to be able to choose a Python minor version or use the latest Python.

**Comment by fdiblen** [comment]
Fixed in https://github.com/matchms/matchms/pull/223
