### ISSUE TITLE
Filtering should not change spectrum in-place

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms-backup#86]
Currently we're writing filters that adjust spectrum members in-place. This may be good for performance, but on the downside it is also an opaque way of altering objects.

I'd like some input from others on this.

**Comment by cwmeijer** [comment]
Change this so we don't touch the input of the function and the result should be returned by the filter.
This will also make it easier to compute distributed later.

**Comment by florian-huber** [comment]
I think it would indeed be cleaner to not touch the input. But then the workflow described in #67 could become a bit more cumbersome, right? Would it then look a bit like this?

```python

import os
from matchms.importing import load_from_mgf
from matchms.filtering import filterfun1, filterfun2


def filtering_workflow():

    def apply_filters(s_in):
        s_out = filterfun1(s_in)
        s_out = filterfun2(s_out)
        return s_out

    # loading
    module_root = os.path.join(os.path.dirname(__file__), '..')
    references_file = os.path.join(module_root, 'tests', 'pesticides.mgf')

    reference_spectrums_raw = load_from_mgf(references_file)
    reference_spectrums = [s.clone() for s in reference_spectrums_raw]

    query_spectrum_raw = reference_spectrums_raw[0]
    query_spectrum = query_spectrum_raw.clone()

    # filtering
    for s in reference_spectrums:
        s = apply_filters(s)

    query_spectrum = apply_filters(query_spectrum)
...
```

**Comment by jspaaks** [comment]
probably more simple, more like this (untested)

```python

import os
from matchms.importing import load_from_mgf
from matchms.filtering import filterfun1, filterfun2


def filtering_workflow():

    def apply_filters(s):
        s = filterfun1(s)
        s = filterfun2(s)
        return s

    # loading
    module_root = os.path.join(os.path.dirname(__file__), '..')
    references_file = os.path.join(module_root, 'tests', 'pesticides.mgf')

    reference_spectrums = [apply_filters(s) for s in load_from_mgf(references_file)]

    query_spectrum = reference_spectrums[0].clone()

```

**Comment by florian-huber** [comment]
Looks good. Just need to add the ``spectrum = spectrum.clone()`` part again to the filter functions (and the return part of course). No big thing, but it will still change all filter functions and tests slightly. Probably not make this part of #73 or what do you think?

**Comment by jspaaks** [comment]
@florian-huber this should definitely not be part of #73. Pull requests should be small and focused.

**Comment by jspaaks** [comment]
PR #100
