### ISSUE TITLE
Add code analysis tool

### ISSUE THREAD

**Issue by fdiblen** [matchms/matchms-backup#9]
Add Codacy or similar tools for code analysis. 

Some options are listed in https://github.com/NLeSC/template

**Comment by sverhoeven** [comment]
Look at code coverage after PR #66 is merge

**Comment by HannoSpreeuw** [comment]
From codacy.com ---> Get started.

![image](https://user-images.githubusercontent.com/11661087/78361829-51ccd780-75b9-11ea-96ad-cb7bfefe119e.png)

It seems not wise to login here with my own GH account if we really want to integrate Codacy with all of our GT repos. 
Is there a  GT GH account?

**Comment by HannoSpreeuw** [comment]
But [there's a lot](https://github.com/marketplace/category/code-quality) out there.

**Comment by HannoSpreeuw** [comment]
[Here](https://www.softwaretestinghelp.com/code-review-tools/)'s a nice review of code review tools.

But their list strangely enough does not include Codacy.
Nor Code Climate nor Sonarcloud.

The ones covered in that list do not seem to be the hottest tools around.

**Comment by HannoSpreeuw** [comment]
This morning, I have been looking at Codacy, Code Climate and Sonarcloud.
I like the Sonarcloud dashboard best, it has the clearest layout, in my opinion.

**Comment by HannoSpreeuw** [comment]
I myself cannot seem to run Sonarcloud on matchms, because it seems to require admin permissions.
So I tried to run Sonarcloud on the repositories in my own GH account. But that requires creating an organisation first and then I need to use the paid plan because I have a private repo.

So I would like the matchms administrator to [activate automatic analysis for existing projects](https://sonarcloud.io/documentation/analysis/automatic-analysis/):
```
For existing projects:

    Go to your project’s Administration > Analysis Method page and turn Automatic Analysis on.
```

**Comment by HannoSpreeuw** [comment]
Sorry @fdiblen, I can't find that link to project administration, or did you already activate the automatic analysis?
I can't find any result of that analysis.

Also, the word project is probably misused, I think they mean a repo.

**Comment by fdiblen** [comment]
@HannoSpreeuw I didn't do anything. You will need to add a trigger I think. Maybe you need to add a  configuration file to the repo or activate something in sonar cloud dashboard?

**Comment by sverhoeven** [comment]
1. The Sonar Cloud must be added as a Github app to the GH organization
2. The matchms repository must be included in the repository access list on the SonarCloud settings page on GH.
3. The SonarCloud analysis must be run in Github Actions, see https://github.com/iomega/zenodo-upload/blob/master/.github/workflows/main.yml#L52-L56 for example.

Step 1 and 2 need a organization owner (@fdiblen) and 3 requires a Sonar Token from https://sonarcloud.io/account/security/ .

**Comment by fdiblen** [comment]
closed in #79

**Comment by sverhoeven** [comment]
The issue has been closed too soon, not all features of SonarCloud have been implemented.

There is no
* [ ] analysis run on every push or release in GH Actions
* [x] [code coverage](https://sonarcloud.io/documentation/analysis/coverage/) captured
* [x] [test execution report](https://docs.pytest.org/en/latest/usage.html#creating-junitxml-format-files).
* [x] badge for code coverage

**Comment by sverhoeven** [comment]
When SonarCloud analysis is performed in GH Action the [automatic analysis should be turned off](https://sonarcloud.io/documentation/analysis/automatic-analysis/#conflict-with-ci-based-analysis).

**Comment by fdiblen** [comment]
> When SonarCloud analysis is performed in GH Action the [automatic analysis should be turned off](https://sonarcloud.io/documentation/analysis/automatic-analysis/#conflict-with-ci-based-analysis).

Turned off the automatic analysis.

**Comment by HannoSpreeuw** [comment]
>     1. The Sonar Cloud must be added as a Github app to the GH organization

How can I check if this has been added?
I am looking at the [matchms organization](https://github.com/matchms), but I only see repositories, packages, people, teams and projects.

**Comment by HannoSpreeuw** [comment]
According to the [general information about GH apps](https://developer.github.com/apps/about-apps/):
```
By default, only organization owners can manage the settings of GitHub Apps in an organization. To allow additional users to manage GitHub Apps in an organization, an owner can grant them GitHub App manager permissions.
```
Perhaps I cannot see any installation of Sonar Cloud because I do not have the appropriate permissions.

**Comment by fdiblen** [comment]
@HannoSpreeuw I added Sonarcloud this morning and made you admin. When you login to sonarcloud using your github account, you should be able to see all the settings and change them.

**Comment by fdiblen** [comment]
Btw, we already have a sonarcloud badge in our repo. See the code quality badge.

**Comment by HannoSpreeuw** [comment]
> @HannoSpreeuw I added Sonarcloud this morning and made you admin. When you login to sonarcloud using your github account, you should be able to see all the settings and change them.

Ah thanks, I now understand that this cannot be seen in the GH repo.

**Comment by HannoSpreeuw** [comment]
> The issue has been closed too soon, not all features of SonarCloud have been implemented.
> 
> There is no
> 
>     * [ ]  analysis run on every push or release in GH Actions
> 
>     * [ ]  [code coverage](https://sonarcloud.io/documentation/analysis/coverage/) captured
> 
>     * [ ]  [test execution report](https://docs.pytest.org/en/latest/usage.html#creating-junitxml-format-files).
> 
>     * [ ]  badge for code coverage

@sverhoeven I am currently looking at this dashboard, but it is unclear to me how you can add those features

![image](https://user-images.githubusercontent.com/11661087/78694950-b52e7080-78fd-11ea-9213-c006e218d660.png)

**Comment by sverhoeven** [comment]
GitHub Actions is used in this repo to run the tests/builds, it is configured in [/.github/workflows/ci_build.yml](https://github.com/matchms/matchms/blob/master/.github/workflows/ci_build.yml).

On https://sonarcloud.io/project/analysis_method?id=matchms_matchms you can find in instructions for performing the analysis in a Continuous Integration build job. 
They don't have a tutorial for GitHub actions. but there is https://github.com/SonarSource/sonarcloud-github-action which you can use to run the analysis in GitHub Actions.

**Comment by HannoSpreeuw** [comment]
Just to be absolutely clear, we have not yet picked any CI system yet, have we?

**Comment by HannoSpreeuw** [comment]
I am still a bit puzzled about the `SonarCloud projectKey` mentioned [here](https://github.com/marketplace/actions/sonarcloud-scan). It says:

```
projectKey=<replace with the key generated when setting up the project on SonarCloud>
```
I don't have this key.
@fdiblen Did you generate this key?

**Comment by fdiblen** [comment]
@HannoSpreeuw No, as you claimed this issue, as far as I know,  nobody else did anything.

**Comment by sverhoeven** [comment]
When @fdiblen at the beginning enabled automatic analysis, the https://sonarcloud.io/dashboard?id=matchms_matchms was created. It has `matchms_matchms` as projectKey and `matchms` as organization key.

**Comment by HannoSpreeuw** [comment]
Thanks @sverhoeven, the latter I had found [here](https://sonarcloud.io/account/organizations) but the former I had not been able to find.

**Comment by HannoSpreeuw** [comment]
I guess I should be almost there. The SonarSource link from @sverhoeven shows how to modify .github/workflows/build.yml. He also shared [the link](https://sonarcloud.io/account/security/) for generating a SONAR_TOKEN. I am still struggling with the required [GITHUB_TOKEN](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token). That link says:
```
When you enable GitHub Actions, GitHub installs a GitHub App on your repository. The GITHUB_TOKEN secret is a GitHub App installation access token. 
```
So how do I retrieve the GITHUB_TOKEN?

**Comment by sverhoeven** [comment]
I created PR #149, it is unable to perform sonar analysis due to missing token.

Can @fdiblen or any repo admin create a token at https://sonarcloud.io/account/security/ and add it to https://github.com/matchms/matchms/settings/secrets with name SONAR_TOKEN.
