### ISSUE TITLE
add equivalent filter of min_peaks

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms-backup#90]
https://github.com/matchms/matchms/blob/61602e744be587be98122d5964d5ed75cca2ecba/matchms/old/ms_functions.py#L69-L71

**Comment by fdiblen** [comment]
- [ ] Get a clear description from Florian and add it to this issue
- [ ] Decide if we need need it

**Comment by jspaaks** [comment]
Hi @fdiblen I think Florian discussed this in the video. I can take a stab at this I think with the current information. Basically you want to have a minimum number of peaks for any given spectrum, but then there can be an additional requirement that raises this minimum depending on the parent mass, since you expect heavy parents to yield a greater number of peaks.

This filter will also be the first one that can yield a return argument ``None``, so we should adapt the existing filters as well, such that the first thing they check is if the input spectrum is ``None``, and if so, ``return None`` themselves immediately.
