### ISSUE TITLE
add equivalent filter of merge_energies

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms-backup#91]
https://github.com/matchms/matchms/blob/61602e744be587be98122d5964d5ed75cca2ecba/matchms/old/ms_functions.py#L72-L73

**Comment by fdiblen** [comment]
- [ ] Get a clear description from Florian and add it to this issue
- [ ] Decide if we need need it

**Comment by florian-huber** [comment]
It refers to a very common filter step when processing MS2 spectra. Peaks are merged if they are closer than a resolution threshold (e.g. closer than 1ppm of the mz). They can either be merged by summing up all intensities of the respective peaks, or by only keeping the maximum intensity.

To obtain our current results we did not use this merging step. But to be sure I wrote two collaborators to get their opinion on how much this is a default thing to do in the field.

**Comment by florian-huber** [comment]
Close this since it actually refers to the same filter as #92 .
