### ISSUE TITLE
don't load data from file in unit test

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms-backup#99]
(copied from https://github.com/matchms/matchms/pull/73#pullrequestreview-388954200)

data file should be single spectrum since it supposed to bring to light a single error. Ideally, the datafile has only the minimum set of properties to be useful. We may not even need a data file, we could instantiate a Spectrum for this (fewer moving parts is better). For example like I did here https://github.com/matchms/matchms/blob/9fb639f43f0cf1fa242e2e5cdf0eb5e5efa0f7e7/tests/test_normalize_intensities.py#L8-L16

**Comment by florian-huber** [comment]
The last present unit test that was loading data from the mgf was test_clean_inchis. I changed that in PR #119 which I believe will also then close this issue.
